---
- name: Install Mysql packages
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ db_packages }}"
#/*bind adress??*/

- name: Create Ghost database
  mysql_db: name={{ app_db_name }} state=present

- name: Cleanup users with same name accounts
  mysql_user:
    name: "{{ app_db_user }}"
    host_all: yes
    state: absent


- name: Create database user with password and all database privileges and 'WITH GRANT OPTION'
  mysql_user:
    name: "{{ app_db_user }}"
    password: "{{ app_db_password }}"
    priv: '*.*:ALL,GRANT'
    host: "{{ app_user_ip }}"
    state: present