---
# Service for exposing MySQL
apiVersion: v1
kind: Service
metadata:
  name: ghost-service # logical name of the service, which will also become the DNS name of the service when it is created.
  labels:
    app: ghost
    tier: application
spec:
  type: LoadBalancer
  loadBalancerIP: 34.122.151.178
  selector:
    app: ghost
  ports:
    - port: 2368
      targetPort: 2368
